#
#	MAKEFILE for uC/IP 1.0
#
#	This makes the opjects only.
#


NET_OBJS = 	net.o netbuf.o netrand.o nettimer.o \
		netppp.o netipcp.o netlcp.o netfsm.o \
		netmd5.o netchap.o netchpms.o \
		netpap.o netauth.o netvj.o netip.o \
		neticmp.o nettcp.o

all:	$(NET_OBJS)



# Cleanup
clean:
	rm *.o

